server:
  port: 0 #irá subir em porta randômica/aleatória

spring:
  application:
    name: cliente-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka #informa a onde está eureka server
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}} 
    #gera o id da instancia de forma randômica junto com application name